### ISSUE TITLE
Issues in Data Preparation and Modelling

### ISSUE THREAD

**Issue by abhisheksinghIN** [CNES/decloud#14]
1. After implementing sentinel2_prepare.py;
 
![test1](https://github.com/CNES/decloud/assets/39698770/1122e42e-53d3-4281-b90d-9ecbb3c4b052)

2. But during implementing meraner_processor.py, the following issues are;

root@3dfcdc1d2ec0:/workspace/decloud/decloud/production# python meraner_processor.py --in_s2 workspace/decloud/data/S2_PREPARE/T32TPS/ --in_dem workspad/data/DEM_PREPARE/T32TPS.tif/ --output workspace/decloud/data/output/ --savedmodel workspace/decloud/data/model/merunet_occitanie_pretrained.zip
2024-06-24 08:49:39 (INFO) [pyOTB] Successfully loaded 126 OTB applications
2024-06-24 08:49:39 INFO     Init. S2_TILED product
2024-06-24 08:49:39 INFO     Product is not of type s2 (Exception: Not a S2_TILED product (expected 1 files ending with _FRE_10m.tif))
2024-06-24 08:49:39 INFO     Init. S2_THEIA product
2024-06-24 08:49:39 INFO     Input type is a directory
2024-06-24 08:49:39 INFO     Product is not of type s2 (Exception: workspace/decloud/data/S2_PREPARE/T32TPS/ not a S2_THEIA product : _FRE_B2.tif is mi
2024-06-24 08:49:39 INFO     Init. S2_ESA product
2024-06-24 08:49:39 INFO     Input type is a directory
2024-06-24 08:49:39 INFO     Product is not of type s2 (Exception: workspace/decloud/data/S2_PREPARE/T32TPS/ not a S2_ESA product : _B02_10m.jp2 is mis
Traceback (most recent call last):
  File "/workspace/decloud/decloud/production/meraner_processor.py", line 223, in <module>
    sys.exit(main())
  File "/workspace/decloud/decloud/production/meraner_processor.py", line 217, in main
    meraner_processor(params.il_s1, params.in_s2, params.savedmodel, params.in_dem,
  File "/workspace/decloud/decloud/production/meraner_processor.py", line 73, in meraner_processor
    s2t = s2t_product.get_raster_10m()
AttributeError: 'NoneType' object has no attribute 'get_raster_10m'

**Comment by abhisheksinghIN** [comment]
**After S1_prepare.py; data directory: workspace/decloud/data/S2_PREPARE/T32TPS/SENTINEL2A_20230821-101805-444_L2A_T32TPS_D_V3-1/**
<img width="500" alt="image" src="https://github.com/user-attachments/assets/b49f4563-b140-468a-b7eb-4e9e9a298ef6">

**After S2_prepare.py, data directory: workspace/decloud/data/S1_PREPARE/T32TPS/**
<img width="494" alt="image" src="https://github.com/user-attachments/assets/fe4f26d5-7230-403a-8d83-e471b884a682">

**After the python meraner_processor.py**, This is following error while using the merunet_occitanie_pretrained model;

root@3dfcdc1d2ec0:/workspace/decloud/decloud/production# python meraner_processor.py --in_s2 workspace/decloud/data/S2_PREPARE/T32TPS/SENTINEL2A_20230821-101805-444_L2A_T32TPS_D_V3-1/ --il_s1 workspace/decloud/data/S1_PREPARE/T32TPS/ --in_dem workspace/decloud/data/DEM_PREPARE/T32TPS.tif --output workspace/decloud/data/output/ --savedmodel workspace/decloud/data/model/merunet_occitanie_pretrained/             2024-07-15 13:35:23 (INFO) [pyOTB] Successfully loaded 126 OTB applications
2024-07-15 13:35:23 INFO     Init. S2_TILED product
2024-07-15 13:35:23 INFO     Product is not of type s2 (Exception: Not a S2_TILED product (expected 1 files ending with _FRE_10m.tif))
2024-07-15 13:35:23 INFO     Init. S2_THEIA product
2024-07-15 13:35:23 INFO     Input type is a directory
2024-07-15 13:35:23 INFO     Product is not of type s2 (Exception: workspace/decloud/data/S2_PREPARE/T32TPS/ not a S2_THEIA product : _FRE_B2.tif is missing)
2024-07-15 13:35:23 INFO     Init. S2_ESA product
2024-07-15 13:35:23 INFO     Input type is a directory
2024-07-15 13:35:23 INFO     Product is not of type s2 (Exception: workspace/decloud/data/S2_PREPARE/T32TPS/ not a S2_ESA product : _B02_10m.jp2 is missing)
2024-07-15 13:35:23 INFO     Init. S1_TILED product
2024-07-15 13:35:23 INFO     Product is not of type s1 (Exception: Not a S1_TILED product. File workspace/decloud/data/S1_PREPARE/T32TPS/ not found)
2024-07-15 13:35:23 INFO     Product is not of type s1 (Exception: S1_THEIA.__init__() got an unexpected keyword argument 'verbose')
Traceback (most recent call last):
  File "/workspace/decloud/decloud/production/meraner_processor.py", line 183, in <module>
    sys.exit(main())
  File "/workspace/decloud/decloud/production/meraner_processor.py", line 177, in main
    meraner_processor(params.il_s1, params.in_s2, params.savedmodel, params.in_dem,
  File "/workspace/decloud/decloud/production/meraner_processor.py", line 68, in meraner_processor
    input_s1_products.sort(key=_closest_date, reverse=True)
  File "/workspace/decloud/decloud/production/meraner_processor.py", line 66, in _closest_date
    return abs(s2t_product.get_timestamp() - x.get_timestamp())
AttributeError: 'NoneType' object has no attribute 'get_timestamp'


Can you please verify the pre-processed files and why I am facing this error?

**Comment by remicres** [comment]
Hi @abhisheksinghIN ,

I think that you must provide the absolute paths. Let me know if this fixes the issue

**Comment by BernradMaillard** [comment]
> **After S1_prepare.py; data directory: workspace/decloud/data/S2_PREPARE/T32TPS/SENTINEL2A_20230821-101805-444_L2A_T32TPS_D_V3-1/** <img alt="image" width="500" src="https://private-user-images.githubusercontent.com/39698770/348722025-b49f4563-b140-468a-b7eb-4e9e9a298ef6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NDc4MzcsIm5iZiI6MTcyMjU0NzUzNywicGF0aCI6Ii8zOTY5ODc3MC8zNDg3MjIwMjUtYjQ5ZjQ1NjMtYjE0MC00NjhhLWI3ZWItNGU5ZTlhMjk4ZWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDIxMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZmQ1MmMyZDE3OWVhYTM3MWUwNTlkNzdmMWUyNjcyNWYwNDlmNTliOTY2NDdlM2ZmM2MyOGRiYWIxYjNiMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._jsv_wLQ0W1Q_a9aSsgRGddPpABBlbbHwQIlboeYCU0">
> 
> **After S2_prepare.py, data directory: workspace/decloud/data/S1_PREPARE/T32TPS/** <img alt="image" width="494" src="https://private-user-images.githubusercontent.com/39698770/348722324-fe4f26d5-7230-403a-8d83-e471b884a682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NDc4MzcsIm5iZiI6MTcyMjU0NzUzNywicGF0aCI6Ii8zOTY5ODc3MC8zNDg3MjIzMjQtZmU0ZjI2ZDUtNzIzMC00MDNhLThkODMtZTQ3MWI4ODRhNjgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDIxMjUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwNmVkMTk0Njk0Zjc3NWY2MGVkYTc4ZTQ5N2QwNTcwZDEyZjA3MzBlMDhlZGUzMmZmMTFkMjA3YTU1NzMyYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MPp7IMRD8Pp-9NkABaVwEtyd6VrtvI5FUvp4RKQZKRo">
> 
> **After the python meraner_processor.py**, This is following error while using the merunet_occitanie_pretrained model;
> 
> root@3dfcdc1d2ec0:/workspace/decloud/decloud/production# python meraner_processor.py --in_s2 workspace/decloud/data/S2_PREPARE/T32TPS/SENTINEL2A_20230821-101805-444_L2A_T32TPS_D_V3-1/ --il_s1 workspace/decloud/data/S1_PREPARE/T32TPS/ --in_dem workspace/decloud/data/DEM_PREPARE/T32TPS.tif --output workspace/decloud/data/output/ --savedmodel workspace/decloud/data/model/merunet_occitanie_pretrained/ 2024-07-15 13:35:23 (INFO) [pyOTB] Successfully loaded 126 OTB applications 2024-07-15 13:35:23 INFO Init. S2_TILED product 2024-07-15 13:35:23 INFO Product is not of type s2 (Exception: Not a S2_TILED product (expected 1 files ending with _FRE_10m.tif)) 2024-07-15 13:35:23 INFO Init. S2_THEIA product 2024-07-15 13:35:23 INFO Input type is a directory 2024-07-15 13:35:23 INFO Product is not of type s2 (Exception: workspace/decloud/data/S2_PREPARE/T32TPS/ not a S2_THEIA product : _FRE_B2.tif is missing) 2024-07-15 13:35:23 INFO Init. S2_ESA product 2024-07-15 13:35:23 INFO Input type is a directory 2024-07-15 13:35:23 INFO Product is not of type s2 (Exception: workspace/decloud/data/S2_PREPARE/T32TPS/ not a S2_ESA product : _B02_10m.jp2 is missing) 2024-07-15 13:35:23 INFO Init. S1_TILED product 2024-07-15 13:35:23 INFO Product is not of type s1 (Exception: Not a S1_TILED product. File workspace/decloud/data/S1_PREPARE/T32TPS/ not found) 2024-07-15 13:35:23 INFO Product is not of type s1 (Exception: S1_THEIA.**init**() got an unexpected keyword argument 'verbose') Traceback (most recent call last): File "/workspace/decloud/decloud/production/meraner_processor.py", line 183, in sys.exit(main()) File "/workspace/decloud/decloud/production/meraner_processor.py", line 177, in main meraner_processor(params.il_s1, params.in_s2, params.savedmodel, params.in_dem, File "/workspace/decloud/decloud/production/meraner_processor.py", line 68, in meraner_processor input_s1_products.sort(key=_closest_date, reverse=True) File "/workspace/decloud/decloud/production/meraner_processor.py", line 66, in _closest_date return abs(s2t_product.get_timestamp() - x.get_timestamp()) AttributeError: 'NoneType' object has no attribute 'get_timestamp'
> 
> Can you please verify the pre-processed files and why I am facing this error? Did you update the pre-processing scripts through which we have different filenames saved in S1_PREPARE and S2_PREPARE and the pre-trained model is expecting different filenames?

provide the relative paths, this worked for me.

```
 meraner_processor \
  --il_s1 ./images/S1/S1_PREPARE/s1a_33PUK_vvvh_ASC_161_20231029txxxxxx_from-10to3dB.tif \
  --in_s2 ./images/S2/S2_PREPARE/T33PUK/SENTINEL2B_20231030-093821-936_L2A_T33PUK_C_V3-1/ \
  --in_dem ./images/T33PUK.tif \
  --output OUTPUT.tif \
  --savedmodel ./merunet_burkina_pretrained \
  --pad 256
```
